// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for logging a row via `POST /api/entries`.
 */
export type AdvanceRequest = { 
/**
 * Meters rowed. When omitted, the server defaults to 500 m.
 */
meters: number | null, };
