// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single logged rowing session.
 */
export type Entry = { 
/**
 * Auto-incrementing database identifier.
 */
id: number, 
/**
 * Distance rowed in this entry, in meters.
 */
meters: number, 
/**
 * Timestamp the entry was recorded (SQLite `datetime('now')`, UTC).
 */
created_at: string, };
