// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A geographic coordinate in decimal degrees.
 */
export type LatLng = { 
/**
 * Latitude in degrees.
 */
lat: number, 
/**
 * Longitude in degrees.
 */
lng: number, };
