// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatLng } from "./LatLng";

export type Progress = { total_meters: number, meters_remaining: number, percent_complete: number, position: LatLng, route: Array<LatLng>, trail: Array<LatLng>, };
