// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatLng } from "./LatLng";

/**
 * A snapshot of overall progress along the route.
 */
export type Progress = { 
/**
 * Distance covered along the route so far, in meters (clamped to route length).
 */
total_meters: number, 
/**
 * Distance still remaining to the finish, in meters.
 */
meters_remaining: number, 
/**
 * Fraction of the route completed, as a percentage (0–100).
 */
percent_complete: number, 
/**
 * Current interpolated position of the boat on the route.
 */
position: LatLng, 
/**
 * The full route as an ordered list of waypoints.
 */
route: Array<LatLng>, 
/**
 * The path traveled so far, from the start to `position`.
 */
trail: Array<LatLng>, };
