// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";
import type { Progress } from "./Progress";

/**
 * Full app state, pushed to clients over SSE whenever anything changes.
 */
export type Snapshot = { 
/**
 * Current progress along the route.
 */
progress: Progress, 
/**
 * All logged entries, with the newest first.
 */
entries: Array<Entry>, };
